# Generated by Django 4.1.1 on 2023-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_systemsettings_staff_username_last_digits_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('Not Reported', 'Not Reported'), ('Other', 'Other')], default='Reported', max_length=200, null=True, verbose_name='Application Status'),
        ),
    ]
