# Generated by Django 4.1.1 on 2023-03-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_admission_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='subject_adma',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Additional Mathematics (ADMA)'),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject_art',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Art'),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject_gmd',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Geometric And Mechanical Drawing (GMD)'),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject_literature',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Literature'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('Not Reported', 'Not Reported'), ('Other', 'Other')], default='Reported', max_length=200, null=True, verbose_name='Registration Status'),
        ),
    ]
