# Generated by Django 4.1.1 on 2023-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_admission_subject_adma_admission_subject_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='subject_agric_science',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Agriculture Science'),
        ),
    ]
