# Generated by Django 4.1.1 on 2023-03-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_admission_subject_agric_science'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Not Registered', 'Not Registered'), ('Other', 'Other')], default='Registered', max_length=200, null=True, verbose_name='Registration Status'),
        ),
    ]
