# Generated by Django 4.1.1 on 2023-03-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_alter_admission_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='student_number',
            field=models.ForeignKey(default='', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.studentnumber', verbose_name='Student Number'),
        ),
    ]
